# Used by FOSSA CLI (https://github.com/fossas/fossa-cli)
# Visit https://fossa.com to learn more

version: 3

server: https://app.fossa.com
project: 
  id: github.com/dej611/spid-react-button
  name: spid-react-button
  link: dej611.github.io/spid-react-button/
  url: git@github.com:dej611/spid-react-button.git

targets:
  only:
    - type: npm
      path: .
