name: Weekly providers check

on:
  schedule:
    - cron:  '0 13 * * 1'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2

          - name: Use Node.js
            uses: actions/setup-node@v1
            with:
              node-version: 16

          - uses: actions/cache@v2
            with:
              path: ~/.npm
              key: ${{ runner.os }}-node-16-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                ${{ runner.os }}-node-16-

          - name: Installing dependencies
            run: npm ci

          - name: Build the library
            run: npm run build

          - name: Check the remote providers list
            run: npm run providers:check
